application-description: @project.description@
application-version: @project.version@

server:
  servlet:
    context-path: /
springdoc:
  default-consumes-media-type: "application/json"
  default-produces-media-type: "application/json"
  api-docs:
    # /api-docs endpoint custom path
    path: /usertracking-openapi
  swagger-ui:
    # swagger-ui custom path
    path: /swagger-ui.html
# Packages to include
  packagesToScan: com.example.ecom

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread][%-5level][user-tracking-api]- %logger{36} - %msg%n"
spring:
  application:
    name: user-tracking
  main:
    banner-mode: 'off'
  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 2MB
      # Max Request Size
      max-request-size: 215MB
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: issue
  jackson:
    default-property-inclusion: NON_NULL

  devtools:
    add-properties: true
    livereload:
      enabled: true

  messages:
    basename: i18n/messages
#    basename: i18n/contact-messages,i18n/user-messages
    cache-seconds: -1
    encoding: UTF-8

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  uploadDir: /Users/covanan/Documents/Upload


app:
  write:
    enabled: false